CREATE DATABASE QuanLiTraSua
GO
USE QuanLiTraSua
CREATE TABLE KHACHHANG
(
ID varchar(20) NOT NULL UNIQUE,
HoTen nvarchar(50),
DiaChi nvarchar(50),
SDT varchar(11),
LoaiKH varchar(20),
Email varchar(50),
DiemTichLuy float,
PRIMARY KEY(ID)
)
CREATE TABLE LOAIKHACHHANG
(
ID varchar(20) NOT NULL UNIQUE,
LoaiKhachHang nvarchar(50),
PRIMARY KEY(ID)
)
CREATE TABLE CHITIETHOADON
(
ID_Mon varchar(20) NOT NULL,
ID_HoaDon varchar(20) NOT NULL,
SoLuong int,
GhiChu nvarchar(50),
Size varchar(10),
PRIMARY KEY(ID_Mon,ID_HoaDon)
)
CREATE TABLE CHITIETMON
(
ID_Mon varchar(20) NOT NULL,
ID_NguyenLieu varchar(20)NOT NULL,
PRIMARY KEY(ID_Mon,ID_NguyenLieu)
)
CREATE TABLE HOADON
(
ID varchar(20) NOT NULL UNIQUE,
ID_KhachHang varchar(20),
NgayDat datetime,
HinhThucThanhToan varchar(20),
ID_PhuongThucGiao varchar(20),
DiaChiNhan nvarchar(20),
KT_Ship bit,
PRIMARY KEY(ID)
)
CREATE TABLE MON
(
ID varchar(20) NOT NULL,
TenMon nvarchar(50),
Gia float,
KT_DacBiet bit,
KT_BanChay bit,
PRIMARY KEY(ID)
)
CREATE TABLE NGUYENLIEU
(
ID varchar(20) NOT NULL,
TenNguyenLieu nvarchar(50),
XuatXu nvarchar(50),
NgayNhap datetime,
TinhTrang nvarchar(50),
PRIMARY KEY(ID)
)
CREATE TABLE PHUONGTHUC
(
ID varchar(20) NOT NULL,
TenPhuongThuc nvarchar(50),
PRIMARY KEY(ID)
)
CREATE TABLE SHIP
(
ID_HoaDon varchar(20) NOT NULL,
ID_Shipper varchar(20),
TenNguoiGiao nvarchar(50),
SDTNguoiGiao varchar(11),
SDTNguoiNhan varchar(11),
PRIMARY KEY(ID_HoaDon)
)
CREATE TABLE SHIPPER
(
ID varchar(20) NOT NULL,
HoTen varchar(20),
DiaChi nvarchar(50),
SDT varchar(11),
CtyQuanLi nvarchar(50),
PRIMARY KEY(ID)
)
ALTER TABLE KHACHHANG ADD CONSTRAINT FK_KHACHHANG_LOAIKHACHHANG FOREIGN KEY(LoaiKH) REFERENCES LOAIKHACHHANG(ID) 
ALTER TABLE CHITIETMON ADD CONSTRAINT FK_CHITIETMON_NGUYENLIEU FOREIGN KEY(ID_NguyenLieu) REFERENCES NGUYENLIEU(ID)
ALTER TABLE CHITIETMON ADD CONSTRAINT FK_CHITIETMON_MON FOREIGN KEY(ID_Mon) REFERENCES MON(ID)
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY(ID_KhachHang) REFERENCES KHACHHANG(ID)
ALTER TABLE SHIP ADD CONSTRAINT FK_SHIP_HOADON FOREIGN KEY(ID_HoaDon) REFERENCES HOADON(ID)
ALTER TABLE SHIP ADD CONSTRAINT FK_SHIP_SHIPPER FOREIGN KEY(ID_Shipper) REFERENCES SHIPPER(ID)
ALTER TABLE HOADON ADD CONSTRAINT FK_HOADON_PHUONGTHUC FOREIGN KEY(ID_PhuongThucGiao) REFERENCES PHUONGTHUC(ID)
ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK_CHITIETHOADON_HOADON FOREIGN KEY(ID_HoaDon) REFERENCES HOADON(ID)
ALTER TABLE CHITIETHOADON ADD CONSTRAINT FK_CHITIETHOADON_MON FOREIGN KEY(ID_Mon) REFERENCES MON(ID)


INSERT INTO LOAIKHACHHANG VALUES
('LKH_001',N'Thành viên thường'),
('LKH_002',N'Thành viên VIP')

INSERT INTO PHUONGTHUC VALUES
('PT_001',N'Giao hàng thường'),
('PT_002',N'Giao hàng nhanh')

INSERT INTO SHIPPER VALUES
('S_001',N'Nguyễn Văn A',N'Hồ Chí Minh','0758849921','Grab'),
('S_002',N'Nguyễn Văn B',N'Hồ Chí Minh','0758949822','Go Viet')


INSERT INTO KHACHHANG VALUES
('KH_001',N'Trần Văn An',N'Đồng Nai','08965432162','LKH_001','tva@gmail.com',100),
('KH_002',N'Đỗ Văn Bình',N'HCM',NULL,'LKH_002',NULL,500)

INSERT INTO NGUYENLIEU VALUES
('NL_001',N'Sữa tươi',N'Đồng Nai,Việt Nam','2019-02-03',N'Còn hàng'),
('NL_002',N'Bột chocolate',N'Thái Lan','2019-02-03',N'Còn hàng'),
('NL_003',N'Bột matcha',N'Hà Nội,Việt Nam','2019-03-03',N'Sắp hết hàng'),
('NL_004',N'Trân châu đen',N'HCM,Việt Nam','2019-02-03',N'Hết hàng'),
('NL_005',N'Thạch trái cây',N'HCM,Việt Nam','2019-02-03',N'Còn hàng')

INSERT INTO MON VALUES
('M_001',N'Trà sữa chocolate',20000,0,0)

INSERT INTO CHITIETMON VALUES
('M_001','NL_001'),
('M_001','NL_002')

INSERT INTO HOADON VALUES
('HD_001','KH_001','2019-11-28',N'Tiền mặt','PT_001',N'P12,Q10,HCM',0),
('HD_002','KH_001','2019-11-29',N'Tiền mặt','PT_001',N'P12,Q10,HCM',1)

INSERT INTO SHIP VALUES
('HD_002','S_001',NULL,NULL,'0768805502')

INSERT INTO CHITIETHOADON VALUES
('M_001','HD_001',2,NULL,'M')

